---

image: registry.gitlab.com/pages/hugo/hugo_extended:latest

default:
  before_script:
    - apk add --update --no-cache git go

test:
  script:
    - hugo mod get -u
    - hugo
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  script:
    - hugo mod get -u
    - hugo
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
