baseurl: https://pujol.io
languageCode: en-US
title: Alexandre Pujol
theme: sustain
preserveTaxonomyNames: true
disableRSS: true
watch: true
paginate: 3

params:
  avatar: avatar.png
  author: Alexandre Pujol
  description: |
    Security Research Lead at [The Collaboratory](https://www.collaboratory.ie/). Ph.D from University College Dublin (Ireland). 🇮🇪 🇫🇷
  keywords: "Alexandre,Pujol,Phd,research,UCD,University College Dublin,Polytech Marseille,computer science,engineer,computer security,security,linux,cloud"
  source: https://gitlab.com/roddhjav/roddhjav.gitlab.io
  fingerprint: BBD1 FEA3 F345 B8FC 72E8  5770 5E86 EC77 30DE D671
  base: https://pujol.io

permalinks:
  post: "/:year/:month/:day/:slug"

menu:
  main:
    - name: GPG Keys
      weight: 100
      identifier: keys
      url: /keys

    - name: Blog
      weight: 200
      identifier: blog
      url: /blog

    - name: Research
      identifier: research
      weight: 300
      url: /research

    - name: Publications
      identifier: pub
      weight: 400
      url: /pub

Social:
  gitlab: roddhjav
  github: roddhjav
  twitter: roddhjav
  keybase: roddhjav
  mastodon: https://mamot.fr/@roddhjav
  linkedIn: alexandrepujol
  googlescholar: LMPIGiYAAAAJ&hl
  email: alexandre@pujol.io

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
